let LED0 = magicbit.rgb().range(0, 1)
let LED1 = magicbit.rgb().range(1, 1)
let LED2 = magicbit.rgb().range(2, 1)
let LED3 = magicbit.rgb().range(3, 1)
basic.forever(function () {
    LED0.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    LED0.clear()
    LED1.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    LED1.clear()
    LED2.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    LED2.clear()
    LED3.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    LED3.clear()
})
